# Generated by Django 4.1.2 on 2022-10-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='user',
        ),
    ]
