# Generated by Django 4.1.2 on 2022-11-01 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_alter_build_options_remove_build_buildmachine_and_more'),
        ('machines', '0002_remove_machine_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='build',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='builder.build'),
        ),
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('BUILDING', 'BUILDING'), ('STOPPING', 'STOPPING')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(fields=('host',), name='unique_host'),
        ),
    ]
