# Generated by Django 4.1.2 on 2022-11-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_machine_build_machine_status_machine_unique_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='local',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='machine',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='machine',
            name='static',
            field=models.BooleanField(default=False),
        ),
    ]
