# Generated by Django 4.1.2 on 2022-11-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_alter_machine_build'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='machine',
            table='lbs_machine',
        ),
    ]
