# Generated by Django 4.2.11 on 2024-04-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_alter_machine_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('incus', 'Incus'), ('docker', 'Docker'), ('copr', 'Copr')], max_length=20),
        ),
    ]
