# Generated by Django 4.1.2 on 2022-10-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='use_docker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='windows_installer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='use_docker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='use_lxc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
