# Generated by Django 4.1.2 on 2022-11-01 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_machine_build_machine_status_machine_unique_host'),
        ('projects', '0002_alter_package_use_docker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='use_docker',
        ),
        migrations.AddField(
            model_name='project',
            name='secret',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='machines.machine'),
        ),
        migrations.AlterField(
            model_name='project',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='machines.machine'),
        ),
        migrations.CreateModel(
            name='PackageDependancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependantpackage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependantpackage', to='projects.package')),
                ('requiredpackage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requiredpackage', to='projects.package')),
            ],
        ),
    ]
