# Generated by Django 4.1.2 on 2022-11-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_package_use_docker_project_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_type',
            field=models.CharField(choices=[('github', 'Github'), ('gitlab', 'Gitlab')], default='github', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='secret',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='use_docker',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='use_lxc',
            field=models.BooleanField(default=True),
        ),
    ]
