# Generated by Django 4.1.2 on 2022-11-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_git_type_alter_project_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_private_token',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
