# Generated by Django 4.1.2 on 2022-11-05 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_packagebuildstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagebuildstatus',
            name='sourcehash',
        ),
        migrations.AddField(
            model_name='packagebuildstatus',
            name='arch',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='packagebuildstatus',
            name='distro',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='packagebuildstatus',
            name='release',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='PackageSrcHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.CharField(max_length=250)),
                ('sourcehash', models.CharField(max_length=250)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.package')),
            ],
        ),
    ]
