# Generated by Django 4.1.2 on 2022-11-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_packagebuildstatus_sourcehash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='copr_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
