# Generated by Django 4.1.2 on 2022-11-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_copr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public_key_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
