# Generated by Django 4.1.2 on 2022-11-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='project',
            name='public_key',
        ),
    ]
