# Generated by Django 4.1.2 on 2022-11-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_private_key_remove_project_public_key'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branch',
            table='lbs_branch',
        ),
        migrations.AlterModelTable(
            name='distro',
            table='lbs_distro',
        ),
        migrations.AlterModelTable(
            name='package',
            table='lbs_package',
        ),
        migrations.AlterModelTable(
            name='packagebuildstatus',
            table='lbs_package_build_status',
        ),
        migrations.AlterModelTable(
            name='packagedependancy',
            table='lbs_package_dependancy',
        ),
        migrations.AlterModelTable(
            name='packagesrchash',
            table='lbs_package_src_hash',
        ),
        migrations.AlterModelTable(
            name='project',
            table='lbs_project',
        ),
        migrations.AlterModelTable(
            name='projectfile',
            table='lbs_project_file',
        ),
    ]
