# Generated by Django 3.2.19 on 2023-05-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_branch_table_alter_distro_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='git_type',
            field=models.CharField(choices=[('gitea', 'Gitea'), ('github', 'Github'), ('gitlab', 'Gitlab')], default='github', max_length=20),
        ),
    ]
