# Generated by Django 3.1.9 on 2021-08-06 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'waiting'), ('BUILDING', 'building'), ('CANCELLED', 'cancelled'), ('FINISHED', 'finished')], max_length=20)),
                ('secret', models.BooleanField()),
                ('branchname', models.CharField(max_length=250)),
                ('release', models.CharField(max_length=20)),
                ('arch', models.CharField(max_length=10)),
                ('avoidlxc', models.BooleanField()),
                ('avoiddocker', models.BooleanField()),
                ('dependsOnOtherProjects', models.TextField()),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField()),
                ('hanging', models.BooleanField()),
                ('buildsuccess', models.CharField(max_length=20)),
                ('buildnumber', models.IntegerField()),
                ('buildmachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine')),
                ('distro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.distro')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.package')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ('buildnumber',),
            },
        ),
    ]
