# Generated by Django 4.1.2 on 2022-11-01 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0002_alter_build_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={},
        ),
        migrations.RemoveField(
            model_name='build',
            name='buildmachine',
        ),
        migrations.RemoveField(
            model_name='build',
            name='buildnumber',
        ),
        migrations.AddField(
            model_name='build',
            name='designated_build_machine',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='build',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='build',
            name='buildsuccess',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='build',
            name='dependsOnOtherProjects',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='build',
            name='distro',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='build',
            name='finished',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='build',
            name='hanging',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='build',
            name='package',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='build',
            name='project',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='build',
            name='started',
            field=models.DateTimeField(default=None),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.TextField()),
                ('created', models.DateTimeField()),
                ('build', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='builder.build')),
            ],
        ),
    ]
