# Generated by Django 4.1.2 on 2022-11-04 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_alter_build_options_remove_build_buildmachine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='buildsuccess',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='dependsOnOtherProjects',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='designated_build_machine',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='finished',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='started',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.build'),
        ),
    ]
