# Generated by Django 4.1.2 on 2022-11-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_alter_build_buildsuccess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='avoiddocker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='build',
            name='avoidlxc',
            field=models.BooleanField(default=False),
        ),
    ]
