# Generated by Django 4.1.2 on 2022-11-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_alter_build_avoiddocker_alter_build_avoidlxc'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='number',
            field=models.IntegerField(default=-1),
        ),
    ]
