# Generated by Django 4.1.2 on 2022-11-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_build_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='build',
            table='lbs_build',
        ),
        migrations.AlterModelTable(
            name='log',
            table='lbs_log',
        ),
    ]
